import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { ArgumentResult, ArgumentResultSchema } from "../schemas/argument.js";
import { ResearchResult } from "../schemas/research.js";
import { ChannelConfig } from "../schemas/channel.js";

export class ArgumentAgent {
  /**
   * Loads and validates the editorial thesis / argument artifact generated by the Antigravity Argument Agent.
   * Emits companion argument/argument.md if missing.
   */
  public async loadOrValidate(outputDir: string = process.cwd()): Promise<ArgumentResult> {
    const argumentDir = join(outputDir, "argument");
    const jsonPath = join(argumentDir, "argument.json");
    const mdPath = join(argumentDir, "argument.md");

    if (!existsSync(jsonPath)) {
      throw new Error(
        `[ARGUMENT AGENT] Missing argument artifact at ${jsonPath}.\n` +
        `The Antigravity Argument Agent must synthesize the research into an editorial thesis ` +
        `conforming to ArgumentResultSchema at argument/argument.json.`
      );
    }

    try {
      const raw = readFileSync(jsonPath, "utf-8");
      const parsed = JSON.parse(raw);
      const validated = ArgumentResultSchema.parse(parsed);

      console.log(`[ARGUMENT] Verified editorial argument: "${validated.centralThesis}"`);
      console.log(`  - Central question: "${validated.centralQuestion}"`);
      console.log(`  - Supporting claims: ${validated.supportingClaims.length}`);
      console.log(`  - Counterarguments addressed: ${validated.counterArguments.length}`);
      console.log(`  - Narrative progression phases: ${validated.narrativeProgression.length}`);
      console.log(`  - Recommended runtime depth: ${validated.estimatedDepthMinutes} minutes`);

      if (!existsSync(mdPath)) {
        this.generateMarkdown(validated, mdPath);
      }

      return validated;
    } catch (err: any) {
      throw new Error(`[ARGUMENT AGENT] Argument validation failed at ${jsonPath}: ${err.message}`);
    }
  }

  private generateMarkdown(argument: ArgumentResult, mdPath: string): void {
    const lines: string[] = [
      `# Editorial Argument: ${argument.topic}`,
      ``,
      `## Central Question`,
      `> ${argument.centralQuestion}`,
      ``,
      `## Overarching Thesis`,
      `**${argument.centralThesis}**`,
      ``,
      `*Recommended Documentary Depth:* **${argument.estimatedDepthMinutes} minutes**`,
      ``,
      `## Supporting Claims & Empirical Backing`,
      ...argument.supportingClaims.map((c, i) =>
        `### Claim ${i + 1}: ${c.claim} [${c.category} - ${c.strength.toUpperCase()}]\n` +
        c.evidence.map((e) => `- *Evidence:* ${e}`).join("\n")
      ),
      ``,
      `## Counter-Arguments & Contextual Nuance`,
      ...argument.counterArguments.map((ca, i) =>
        `### Position ${i + 1}: ${ca.position}\n` +
        `- **Rebuttal / Clarification:** ${ca.rebuttal}\n` +
        `- **Evidence Gap / Unknown:** ${ca.evidenceGap}`
      ),
      ``,
      `## Narrative Progression Structure`,
      ...argument.narrativeProgression.map((p, i) =>
        `### Act / Beat ${i + 1}: ${p.phase.toUpperCase()} — ${p.purpose}\n` +
        p.keyPoints.map((kp) => `- ${kp}`).join("\n") +
        `\n- ➡️ **Transition:** *${p.transitionQuestion}*`
      ),
      ``,
      `## Final Synthesis`,
      argument.conclusion
    ];

    writeFileSync(mdPath, lines.join("\n"), "utf-8");
    console.log(`[ARGUMENT] Emitted companion argument markdown to ${mdPath}`);
  }
}
