import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { ResearchResult, ResearchResultSchema } from "../schemas/research.js";

export class ResearchAgent {
  /**
   * Loads and validates the research dossier generated by the Antigravity Research Agent.
   * If research/research.json does not exist, throws with structured instructions for Antigravity.
   */
  public async loadOrValidate(topic: string, outputDir: string = process.cwd()): Promise<ResearchResult> {
    const researchDir = join(outputDir, "research");
    const jsonPath = join(researchDir, "research.json");
    const mdPath = join(researchDir, "research.md");

    if (!existsSync(jsonPath)) {
      throw new Error(
        `[RESEARCH AGENT] Missing research artifact at ${jsonPath}.\n` +
        `The Antigravity Research Agent must research the topic "${topic}" and emit a verified ` +
        `research dossier matching ResearchResultSchema at research/research.json.`
      );
    }

    try {
      const raw = readFileSync(jsonPath, "utf-8");
      const parsed = JSON.parse(raw);
      const validated = ResearchResultSchema.parse(parsed);

      console.log(`[RESEARCH] Successfully verified research dossier for topic: "${validated.topic}"`);
      console.log(`  - Facts: ${validated.facts.length}`);
      console.log(`  - Statistics: ${validated.statistics.length}`);
      console.log(`  - Timeline events: ${validated.timeline.length}`);
      console.log(`  - Primary sources: ${validated.sources.length}`);

      // Ensure research.md markdown companion exists
      if (!existsSync(mdPath)) {
        this.generateMarkdownSummary(validated, mdPath);
      }

      return validated;
    } catch (err: any) {
      throw new Error(`[RESEARCH AGENT] Research validation failed at ${jsonPath}: ${err.message}`);
    }
  }

  private generateMarkdownSummary(research: ResearchResult, mdPath: string): void {
    const lines: string[] = [
      `# Research Dossier: ${research.topic}`,
      ``,
      `**Editorial Angle:** ${research.angle}`,
      ``,
      `## Executive Summary`,
      research.summary,
      ``,
      `## Verified Facts & Categorized Claims`,
      ...research.facts.map((f, i) => `${i + 1}. **[${f.category}]** (Confidence: ${(f.confidence * 100).toFixed(0)}%) ${f.statement}\n   *Source: ${f.source.title} (${f.source.url})*`),
      ``,
      `## Key Statistics`,
      ...research.statistics.map((s) => `- **${s.metric}**: \`${s.value}\` (${s.context})`),
      ``,
      `## Timeline of Key Developments`,
      ...research.timeline.map((t) => `- **${t.date}**: ${t.event} — *${t.significance}*`),
      ``,
      `## Sources Cited`,
      ...research.sources.map((src) => `- [${src.title}](${src.url})`)
    ];

    writeFileSync(mdPath, lines.join("\n"), "utf-8");
    console.log(`[RESEARCH] Emitted companion dossier markdown to ${mdPath}`);
  }
}
